// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyLrHpkZKM30Q0T9s1Qwk9SimmHNhddR4',
    appId: '1:653094787887:web:1e0ae1c7820e913acc5fda',
    messagingSenderId: '653094787887',
    projectId: 'chatapp-eb665',
    authDomain: 'chatapp-eb665.firebaseapp.com',
    storageBucket: 'chatapp-eb665.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQRpAKFvXDG1C-wGbhGyCiHSWumZbinQA',
    appId: '1:653094787887:android:35c552145dae857ecc5fda',
    messagingSenderId: '653094787887',
    projectId: 'chatapp-eb665',
    storageBucket: 'chatapp-eb665.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC53treCV8ssPOOWQinsQzurOzIt4WMDmg',
    appId: '1:653094787887:ios:3cd514ac3c8b8756cc5fda',
    messagingSenderId: '653094787887',
    projectId: 'chatapp-eb665',
    storageBucket: 'chatapp-eb665.appspot.com',
    iosBundleId: 'com.example.whatsapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC53treCV8ssPOOWQinsQzurOzIt4WMDmg',
    appId: '1:653094787887:ios:4466dfbd5efdc53acc5fda',
    messagingSenderId: '653094787887',
    projectId: 'chatapp-eb665',
    storageBucket: 'chatapp-eb665.appspot.com',
    iosBundleId: 'com.example.whatsapp.RunnerTests',
  );
}
